version: '3.7'
services:
  mongodb_container:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    # ports:
    #   - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped
    network_mode: host

volumes:
  mongodb_data_container:
